name: CI/CD Pipeline (GDAL Alternative)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "18"

jobs:
  # Code quality checks with conda GDAL
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ env.PYTHON_VERSION }}
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install GDAL via conda
      shell: bash -el {0}
      run: |
        conda install -c conda-forge gdal>=3.6.0 rasterio fiona shapely geopandas
        
    - name: Install Python dependencies
      shell: bash -el {0}
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety
        # Install remaining requirements that don't conflict with conda GDAL
        pip install torch torchvision numpy scipy matplotlib seaborn plotly
        pip install scikit-learn opencv-python pillow scikit-image
        pip install fastapi uvicorn pydantic python-multipart
        pip install pytest pytest-asyncio pytest-cov pytest-mock httpx
        
    - name: Run Black formatter check
      shell: bash -el {0}
      run: black --check --diff src tests
      
    - name: Run isort import sorter check
      shell: bash -el {0}
      run: isort --check-only --diff src tests
      
    - name: Run flake8 linter
      shell: bash -el {0}
      run: flake8 src tests
      
    - name: Run MyPy type checker
      shell: bash -el {0}
      run: mypy src